/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Messages.CreatePersonelRoomMessage;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import Messages.Message;

/**
 *
 * @author Enes Kızılcın <nazifenes.kizilcin@stu.fsm.edu.tr>
 */
public class AllUsersMenu extends javax.swing.JPanel {

    /**
     * Creates new form AllUsersMenu
     */
    ChattApp mainFrame;
    DefaultListModel userListModel;

    //this panel is represents all user menu . Which list the users on server and , services to start messaging with hem
    public AllUsersMenu(ChattApp mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        this.userListModel = new DefaultListModel();
        this.allUsersJL.setModel(userListModel);
    }
    
    //updates the all users list with given list.
    public void UpdateUserListWithGivenList(ArrayList<String> userNames) {
        userListModel.removeAllElements();
        for (String name : userNames) {
            if (name.isBlank() || name.equals(this.mainFrame.client.userName)) {
                continue;
            }
            userListModel.addElement(name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allUsersMenuHeaderLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allUsersJL = new javax.swing.JList<>();
        startPersonalMessagingBTN = new javax.swing.JButton();
        refreshBTN = new javax.swing.JButton();
        returnMenuBTN = new javax.swing.JButton();
        startMessageBTN = new javax.swing.JButton();
        returnBTN = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        allUsersMenuHeaderLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        allUsersMenuHeaderLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allUsersMenuHeaderLBL.setText("ALL USERS");

        jScrollPane1.setViewportView(allUsersJL);

        startPersonalMessagingBTN.setBackground(new java.awt.Color(204, 255, 255));
        startPersonalMessagingBTN.setText("Start Message");
        startPersonalMessagingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPersonalMessagingBTNActionPerformed(evt);
            }
        });

        refreshBTN.setBackground(new java.awt.Color(204, 255, 255));
        refreshBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        refreshBTN.setForeground(new java.awt.Color(0, 0, 0));
        refreshBTN.setText("Refresh");
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTNActionPerformed(evt);
            }
        });

        returnMenuBTN.setText("Return Menu");

        startMessageBTN.setBackground(new java.awt.Color(204, 255, 255));
        startMessageBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startMessageBTN.setForeground(new java.awt.Color(0, 0, 0));
        startMessageBTN.setText("Start Messaging");
        startMessageBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMessageBTNActionPerformed(evt);
            }
        });

        returnBTN.setBackground(new java.awt.Color(204, 255, 255));
        returnBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        returnBTN.setForeground(new java.awt.Color(0, 0, 0));
        returnBTN.setText("Return");
        returnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(allUsersMenuHeaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(startPersonalMessagingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startMessageBTN)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(refreshBTN))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(returnBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(allUsersMenuHeaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(refreshBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(startMessageBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addComponent(returnBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(828, 828, 828)
                .addComponent(startPersonalMessagingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        // when refresh button is clicked, send server to request for all users.
        Message message = new Message(Message.MessageTypes.ALL_USERS);
        this.mainFrame.client.Send(message);
    }//GEN-LAST:event_refreshBTNActionPerformed

    private void startPersonalMessagingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPersonalMessagingBTNActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_startPersonalMessagingBTNActionPerformed

    private void startMessageBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMessageBTNActionPerformed
        // when start messagin clicked. Send server a create personel room request.
        if (allUsersJL.getSelectedValue() == null) {
            return;
        }
        CreatePersonelRoomMessage cprm = new CreatePersonelRoomMessage();
        cprm.creator = this.mainFrame.client.userName;
        cprm.joiner = allUsersJL.getSelectedValue().toString();
        Message message = new Message(Message.MessageTypes.CREATE_PERSONEL_ROOM);
        message.content = cprm;
        this.mainFrame.client.Send(message);
    }//GEN-LAST:event_startMessageBTNActionPerformed

    private void returnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTNActionPerformed
        // TODO add your handling code here:
        this.mainFrame.changeMenu(this.mainFrame.allUsersMenu, this.mainFrame.mainMenu);
    }//GEN-LAST:event_returnBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> allUsersJL;
    private javax.swing.JLabel allUsersMenuHeaderLBL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JButton returnBTN;
    private javax.swing.JButton returnMenuBTN;
    private javax.swing.JButton startMessageBTN;
    private javax.swing.JButton startPersonalMessagingBTN;
    // End of variables declaration//GEN-END:variables
}
