/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Messages.CreateRoomMessage;
import Messages.JoinRoomMessage;
import Messages.Message;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Enes Kızılcın <nazifenes.kizilcin@stu.fsm.edu.tr>
 */
public class RoomsMenu extends javax.swing.JPanel {

    /**
     * Creates new form RoomChatPanel
     */
    DefaultListModel roomsModel;
    ChattApp mainFrame;
    
    public RoomsMenu(ChattApp mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        roomsModel = new DefaultListModel();
        roomList.setModel(roomsModel);
    }
    
    public void UpdateRoomListWithGivenList(ArrayList<String> roomNames)
    {
        roomsModel.removeAllElements();
        if(roomNames.isEmpty())
        {
            return;
        }
        for (String name : roomNames) {
            roomsModel.addElement(name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomsMenuLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        createNewRoomBTN = new javax.swing.JButton();
        createRoomNameLBL = new javax.swing.JLabel();
        newRoomNameINP = new javax.swing.JTextField();
        createNewRoomHeaderLBL = new javax.swing.JLabel();
        refreshRoomListBTN = new javax.swing.JButton();
        joinRoomBTN = new javax.swing.JButton();
        returnMainMenuBTN = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        roomsMenuLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        roomsMenuLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomsMenuLBL.setText("Rooms");

        jScrollPane2.setViewportView(roomList);

        createNewRoomBTN.setBackground(new java.awt.Color(204, 255, 255));
        createNewRoomBTN.setForeground(new java.awt.Color(51, 51, 51));
        createNewRoomBTN.setText("CREATE");
        createNewRoomBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewRoomBTNActionPerformed(evt);
            }
        });

        createRoomNameLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createRoomNameLBL.setText("Room Name");

        newRoomNameINP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRoomNameINPActionPerformed(evt);
            }
        });

        createNewRoomHeaderLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        createNewRoomHeaderLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createNewRoomHeaderLBL.setText("NEW ROOM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createRoomNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newRoomNameINP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(createNewRoomBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(createNewRoomHeaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(createNewRoomHeaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createRoomNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newRoomNameINP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createNewRoomBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        refreshRoomListBTN.setBackground(new java.awt.Color(204, 255, 255));
        refreshRoomListBTN.setForeground(new java.awt.Color(51, 51, 51));
        refreshRoomListBTN.setText("REFRESH");
        refreshRoomListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshRoomListBTNActionPerformed(evt);
            }
        });

        joinRoomBTN.setBackground(new java.awt.Color(204, 255, 255));
        joinRoomBTN.setForeground(new java.awt.Color(51, 51, 51));
        joinRoomBTN.setText("JOIN");
        joinRoomBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinRoomBTNActionPerformed(evt);
            }
        });

        returnMainMenuBTN.setBackground(new java.awt.Color(204, 255, 255));
        returnMainMenuBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        returnMainMenuBTN.setForeground(new java.awt.Color(0, 0, 0));
        returnMainMenuBTN.setText("RETURN");
        returnMainMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMainMenuBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(returnMainMenuBTN)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refreshRoomListBTN)
                            .addComponent(joinRoomBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(roomsMenuLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roomsMenuLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(refreshRoomListBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(joinRoomBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnMainMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createNewRoomBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewRoomBTNActionPerformed
        // when this button is clicked, a new room will be created on server.
        //control input
        //...
        if(newRoomNameINP.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Room name can not be empty!");
            return;
        }
        //...
        //finish control input
        //create message for create rooom and send to the server.
        CreateRoomMessage crm = new CreateRoomMessage(this.mainFrame.client.userName,newRoomNameINP.getText().toString());
        Message message = new Message(Message.MessageTypes.CREATE_ROOM);
        message.content = crm;
        this.mainFrame.client.Send(message);
    }//GEN-LAST:event_createNewRoomBTNActionPerformed

    private void refreshRoomListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshRoomListBTNActionPerformed
        // when this buton is clicked all rooms message send to server to refresh list
        //with new rooms.
        Message message = new Message(Message.MessageTypes.ALL_ROOMS);
        this.mainFrame.client.Send(message);
    }//GEN-LAST:event_refreshRoomListBTNActionPerformed

    private void returnMainMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMainMenuBTNActionPerformed
        //if return button is clicked then go backto main menu.
        newRoomNameINP.setText("");
        roomsModel.removeAllElements();
        this.mainFrame.changeMenu(this.mainFrame.roomsMenu,this.mainFrame.mainMenu);
    }//GEN-LAST:event_returnMainMenuBTNActionPerformed

    private void joinRoomBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinRoomBTNActionPerformed
        // if this button is clicked, then a join room request sends to server .
        if(roomList.getSelectedValue() == null)return;
        System.out.println("Selected Value is not empty");
        String chosenRoom = roomList.getSelectedValue();
        Message message = new Message(Message.MessageTypes.JOIN_ROOM);
        JoinRoomMessage jrm = new JoinRoomMessage(this.mainFrame.client.userName,chosenRoom);
        message.content = jrm;
        this.mainFrame.client.Send(message);
        System.out.println("Join Room Message Sended");
    }//GEN-LAST:event_joinRoomBTNActionPerformed

    private void newRoomNameINPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRoomNameINPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newRoomNameINPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewRoomBTN;
    private javax.swing.JLabel createNewRoomHeaderLBL;
    private javax.swing.JLabel createRoomNameLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton joinRoomBTN;
    private javax.swing.JTextField newRoomNameINP;
    private javax.swing.JButton refreshRoomListBTN;
    private javax.swing.JButton returnMainMenuBTN;
    private javax.swing.JList<String> roomList;
    private javax.swing.JLabel roomsMenuLBL;
    // End of variables declaration//GEN-END:variables
}
