/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import ClientSide.Client;
import Messages.Message;

/**
 *
 * @author Enes Kızılcın <nazifenes.kizilcin@stu.fsm.edu.tr>
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    ChattApp mainFrame;
    public MainMenu(ChattApp mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuHeader = new javax.swing.JLabel();
        roomsBTN = new javax.swing.JButton();
        usersBTN = new javax.swing.JButton();

        setForeground(new java.awt.Color(0, 153, 0));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));

        mainMenuHeader.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        mainMenuHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuHeader.setText("MAIN MENU");

        roomsBTN.setBackground(new java.awt.Color(204, 255, 255));
        roomsBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        roomsBTN.setForeground(new java.awt.Color(0, 0, 0));
        roomsBTN.setText("Rooms");
        roomsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomsBTNActionPerformed(evt);
            }
        });

        usersBTN.setBackground(new java.awt.Color(204, 255, 255));
        usersBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        usersBTN.setForeground(new java.awt.Color(0, 0, 0));
        usersBTN.setText("Users");
        usersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roomsBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(usersBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(mainMenuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainMenuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(roomsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(usersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roomsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomsBTNActionPerformed
        // TODO add your handling code here:
        Message msg = new Message(Message.MessageTypes.ALL_ROOMS);
        
        this.mainFrame.client.Send(msg);
        this.mainFrame.changeMenu(this.mainFrame.mainMenu, this.mainFrame.roomsMenu);
        
    }//GEN-LAST:event_roomsBTNActionPerformed

    private void usersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBTNActionPerformed
        // TODO add your handling code here:
        Message message = new Message(Message.MessageTypes.ALL_USERS);
        this.mainFrame.client.Send(message);
        this.mainFrame.changeMenu(this.mainFrame.mainMenu, this.mainFrame.allUsersMenu);
    }//GEN-LAST:event_usersBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel mainMenuHeader;
    private javax.swing.JButton roomsBTN;
    private javax.swing.JButton usersBTN;
    // End of variables declaration//GEN-END:variables
}
