/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Messages.CreateRoomMessage;
import Messages.Message;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Enes Kızılcın <nazifenes.kizilcin@stu.fsm.edu.tr>
 */
public class RoomsMenu extends javax.swing.JPanel {

    /**
     * Creates new form RoomChatPanel
     */
    DefaultListModel roomsModel;
    ChattApp mainFrame;
    
    public RoomsMenu(ChattApp mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        roomsModel = new DefaultListModel();
        roomList.setModel(roomsModel);
    }
    
    public void UpdateRoomListWithGivenList(ArrayList<String> roomNames)
    {
        roomsModel.removeAllElements();
        if(roomNames.isEmpty())
        {
            return;
        }
        for (String name : roomNames) {
            roomsModel.addElement(name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomsMenuLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        createNewRoomBTN = new javax.swing.JButton();
        createNewRoomHeaderLBL = new javax.swing.JLabel();
        createRoomNameLBL = new javax.swing.JLabel();
        newRoomNameINP = new javax.swing.JTextField();
        refreshRoomListBTN = new javax.swing.JButton();
        joinRoomBTN = new javax.swing.JButton();
        returnMainMenuBTN = new javax.swing.JButton();

        roomsMenuLBL.setText("Room Name");

        jScrollPane2.setViewportView(roomList);

        createNewRoomBTN.setText("CREATE");
        createNewRoomBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewRoomBTNActionPerformed(evt);
            }
        });

        createNewRoomHeaderLBL.setText("NEW ROOM");

        createRoomNameLBL.setText("Room Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createRoomNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newRoomNameINP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createNewRoomBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createNewRoomHeaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNewRoomHeaderLBL)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createRoomNameLBL)
                    .addComponent(newRoomNameINP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createNewRoomBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        refreshRoomListBTN.setText("REFRESH");
        refreshRoomListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshRoomListBTNActionPerformed(evt);
            }
        });

        joinRoomBTN.setText("JOIN");
        joinRoomBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinRoomBTNActionPerformed(evt);
            }
        });

        returnMainMenuBTN.setText("RETURN");
        returnMainMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMainMenuBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(roomsMenuLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refreshRoomListBTN)
                            .addComponent(joinRoomBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnMainMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(roomsMenuLBL)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(refreshRoomListBTN)
                                .addGap(53, 53, 53)
                                .addComponent(joinRoomBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnMainMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createNewRoomBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewRoomBTNActionPerformed
        // TODO add your handling code here:
        if(newRoomNameINP.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Room name can not be empty!");
            return;
        }
        CreateRoomMessage crm = new CreateRoomMessage(this.mainFrame.client.userName,newRoomNameINP.getText().toString());
        Message message = new Message(Message.MessageTypes.CREATE_ROOM);
        message.content = crm;
        this.mainFrame.client.Send(message);
    }//GEN-LAST:event_createNewRoomBTNActionPerformed

    private void refreshRoomListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshRoomListBTNActionPerformed
        // TODO add your handling code here:
        Message message = new Message(Message.MessageTypes.ALL_ROOMS);
        this.mainFrame.client.Send(message);
    }//GEN-LAST:event_refreshRoomListBTNActionPerformed

    private void returnMainMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMainMenuBTNActionPerformed
        newRoomNameINP.setText("");
        roomsModel.removeAllElements();
        this.mainFrame.changeMenu(this.mainFrame.roomsMenu,this.mainFrame.mainMenu);
    }//GEN-LAST:event_returnMainMenuBTNActionPerformed

    private void joinRoomBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinRoomBTNActionPerformed
        // TODO add your handling code here:
        String chosenRoom;
    }//GEN-LAST:event_joinRoomBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewRoomBTN;
    private javax.swing.JLabel createNewRoomHeaderLBL;
    private javax.swing.JLabel createRoomNameLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton joinRoomBTN;
    private javax.swing.JTextField newRoomNameINP;
    private javax.swing.JButton refreshRoomListBTN;
    private javax.swing.JButton returnMainMenuBTN;
    private javax.swing.JList<String> roomList;
    private javax.swing.JLabel roomsMenuLBL;
    // End of variables declaration//GEN-END:variables
}
